### ISSUE TITLE
Issue with installing forestlas in anaconda

### ISSUE THREAD

**Issue by ShukhratSh** [philwilkes/forestlas#1]
Hello,
Thank you very much for providing this package. I would like to use it for my research to extract a number of forest strata from my point cloud. I am having following error while installing in anaconda.
`pip install git+https://github.com/philwilkes/forestlas
Collecting git+https://github.com/philwilkes/forestlas
  Cloning https://github.com/philwilkes/forestlas to \pip-req-build-h3d4olvh
  Running command git clone -q https://github.com/philwilkes/forestlas '\Temp\pip-req-build-h3d4olvh'
    ERROR: Command errored out with exit status 1:
     command: '\Continuum\anaconda2\envs\myenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'\\pip-req-build-h3d4olvh\\setup.py'"'"'; __file__='"'"\\pip-req-build-h3d4olvh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base '\Temp\pip-req-build-h3d4olvh\pip-egg-info'
         cwd: \pip-req-build-h3d4olvh\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "\pip-req-build-h3d4olvh\setup.py", line 12, in <module>
        long_description=open('README.txt').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by philwilkes** [comment]
setup.py was looking for a README.txt when the README file has a .md suffix. Have updated setup.py
